version: '3.7'

services:
  postgres:
    container_name: 'postgres'
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "scrumble"

  scrumble:
    container_name: 'scrumble'
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  jaeger:
    container_name: 'jaeger'
    image: jaegertracing/all-in-one:latest
    ports:
      - '6831:6831/udp'
      - '6832:6832/udp'
